#script for different preprocessing schemes
data[col] = data[col].str.replace(r"what's", "what is ")
data[col] = data[col].str.replace(r"\'ve", " have ")
data[col] = data[col].str.replace(r"can't", "cannot ")
data[col] = data[col].str.replace(r"n't", " not ")
data[col] = data[col].str.replace(r"i'm", "i am ")
data[col] = data[col].str.replace(r"\'re", " are ")
data[col] = data[col].str.replace(r"\'d", " would ")
data[col] = data[col].str.replace(r"\'ll", " will ")
data[col] = data[col].str.replace(r"\'scuse", " excuse ")
data[col] = data[col].str.replace(r"\'s", " ")
data[col] = data[col].str.replace('\n', ' \n ')
data[col] = data[col].str.replace(r'([a-zA-Z]+)([/!?.])([a-zA-Z]+)', r'\1 \2 \3')
data[col] = data[col].str.replace(r'([*!?\'])\1\1{2,}', r'\1\1\1')
data[col] = data[col].str.replace(r'([*!?\']+)', r' \1 ')
data[col] = data[col].str.replace(r'([a-zA-Z])\1{2,}\b', r'\1\1')
data[col] = data[col].str.replace(r'([a-zA-Z])\1\1{2,}\B', r'\1\1\1')