defaults:
  - hydra/sweeper: optuna

hydra:
  sweeper:
    optuna_config:
      direction: maximize
      study_name: jigsaw
      storage: null
      n_trials: 20
      n_jobs: 1
      sampler: tpe
      seed: 2022